---
abstract: 'easy database connections for Dancer applications'
author:
  - 'celogeek <me@celogeek.com>'
build_requires:
  Dancer: 0
  Dancer::Test: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300017, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Redis
requires:
  Carp: 0
  Dancer::Plugin: 0
  Data::Dumper: 0
  Redis: 1.951
  Try::Tiny: 0
  parent: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/celogeek/Dancer-Plugin-Redis.git
version: 0.12
