---
abstract: 'easy database connections for Dancer applications'
author:
  - 'Celogeek <geistteufel@yahoo.fr>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Redis
requires:
  Carp: 0
  Dancer::Plugin: 0
  Data::Dumper: 0
  LWP::Protocol::https: 0
  Redis: 0
  Template: 0
  Try::Tiny: 0
  perl: 5.006
  strict: 0
  warnings: 0
version: 0.03
